/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as SQRLFaucetContractJson } from "../SQRLFaucet.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace SQRLFaucetTypes {
  export type Fields = {
    symbol: HexString;
    name: HexString;
    decimals: bigint;
    supply: bigint;
    owner: Address;
    balance: bigint;
  };

  export type State = ContractState<Fields>;

  export type WithdrawEvent = ContractEvent<{ to: Address; amount: bigint }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    balance: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  SQRLFaucetInstance,
  SQRLFaucetTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as SQRLFaucetTypes.Fields;
  }

  eventIndex = { Withdraw: 0 };
  consts = { ErrorCodes: { InvalidAmount: BigInt(0) } };

  at(address: string): SQRLFaucetInstance {
    return new SQRLFaucetInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParams<SQRLFaucetTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getSymbol", params);
    },
    getName: async (
      params: Omit<
        TestContractParams<SQRLFaucetTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getName", params);
    },
    getDecimals: async (
      params: Omit<
        TestContractParams<SQRLFaucetTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParams<SQRLFaucetTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getTotalSupply", params);
    },
    balance: async (
      params: Omit<
        TestContractParams<SQRLFaucetTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "balance", params);
    },
    withdraw: async (
      params: TestContractParams<SQRLFaucetTypes.Fields, { amount: bigint }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "withdraw", params);
    },
  };
}

// Use this object to test and deploy the contract
export const SQRLFaucet = new Factory(
  Contract.fromJson(
    SQRLFaucetContractJson,
    "=20-2+9a=101+aa000=1+e02175468652063757272656e742062616c616e63652069732000=11+8=1+e0140245468652063616c6c6572206973206e6f742074686520636f6e7472616374206f776e6572=56",
    "536fedead7c895ceabcee927b3c8f199a16f8f62630cbfc2789a8d1c578a9e19"
  )
);

// Use this class to interact with the blockchain
export class SQRLFaucetInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<SQRLFaucetTypes.State> {
    return fetchContractState(SQRLFaucet, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeWithdrawEvent(
    options: EventSubscribeOptions<SQRLFaucetTypes.WithdrawEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SQRLFaucet.contract,
      this,
      options,
      "Withdraw",
      fromCount
    );
  }

  methods = {
    getSymbol: async (
      params?: SQRLFaucetTypes.CallMethodParams<"getSymbol">
    ): Promise<SQRLFaucetTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        SQRLFaucet,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: SQRLFaucetTypes.CallMethodParams<"getName">
    ): Promise<SQRLFaucetTypes.CallMethodResult<"getName">> => {
      return callMethod(
        SQRLFaucet,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: SQRLFaucetTypes.CallMethodParams<"getDecimals">
    ): Promise<SQRLFaucetTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        SQRLFaucet,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: SQRLFaucetTypes.CallMethodParams<"getTotalSupply">
    ): Promise<SQRLFaucetTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        SQRLFaucet,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    balance: async (
      params?: SQRLFaucetTypes.CallMethodParams<"balance">
    ): Promise<SQRLFaucetTypes.CallMethodResult<"balance">> => {
      return callMethod(
        SQRLFaucet,
        this,
        "balance",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends SQRLFaucetTypes.MultiCallParams>(
    calls: Calls
  ): Promise<SQRLFaucetTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      SQRLFaucet,
      this,
      calls,
      getContractByCodeHash
    )) as SQRLFaucetTypes.MultiCallResults<Calls>;
  }
}
